/**
 * Phase-Actor Authorization Engine
 *
 * Enforces the file ownership model from coordination-rules.md at the plugin level.
 * Converts the "honor system" of Expected Next Writer checks into structural gates.
 *
 * Each file in .agent-memory/ has exactly one writing actor per phase.
 * This module provides:
 *   - canActorWriteFile: check if an actor is allowed to write a file in the current phase
 *   - allowedActorsForFile: return the set of actors allowed to write a given file
 *   - guardFileWrite: returns a block reason if the write should be denied
 */

import type { GraphStateLike } from '../types.js';

// ─── File Ownership Registry ────────────────────────────────────
// Maps file path suffixes to the actor(s) allowed to write them.
// Based on coordination-rules.md Ownership Table.

type FileRule = {
  owners: string[];            // Actor names allowed to write
  phaseRestriction?: string;   // Optional: only allowed in this phase
  coOwners?: string[];         // Actors who can also write under specific conditions
  note?: string;
};

const FILE_OWNERSHIP: Record<string, FileRule> = {
  // ── Planner-owned files ──
  'task.md': {
    owners: ['harness-orchestrator', 'planning-manager', 'feature-planner', 'capability-planner'],
    phaseRestriction: 'planning',
    note: 'harness-orchestrator during init; planning-manager and specialized planners during planning phase',
  },
  'product-spec.md': {
    owners: ['feature-planner'],
    note: 'immutable after feature-planner generates it',
  },
  'features.json': {
    owners: ['feature-planner'],
    note: 'structure immutable; only execution-manager may change passes field',
  },
  'features-summary.md': {
    owners: ['feature-planner'],
  },
  'baseline-source.md': {
    owners: ['capability-planner'],
  },
  'capability-map.md': {
    owners: ['capability-planner'],
  },
  'gap-analysis.md': {
    owners: ['capability-planner'],
  },
  'quality-guardrails.md': {
    owners: ['acceptance-manager', 'harness-orchestrator'],
    note: 'acceptance-manager primary; control escalates',
  },

  // ── Execution-manager-owned files ──
  'round-contract.md': {
    owners: ['execution-manager', 'acceptance-manager'],
    note: 'execution-manager drafts; acceptance-manager reviews in contract negotiation',
  },
  'execution-status.md': {
    owners: ['execution-manager'],
    note: 'capability hands may contribute via evidence-agent but execution-manager owns final write',
  },
  'evidence-ledger.md': {
    owners: ['execution-manager', 'evidence-agent'],
    coOwners: ['code-agent', 'shell-agent', 'browser-agent', 'docs-agent'],
    note: 'evidence-agent is primary writer for evidence normalization',
  },

  // ── Acceptance-manager-owned files ──
  'acceptance-report.md': {
    owners: ['acceptance-manager'],
    note: 'acceptance-manager is the sole judge; probes contribute evidence but do not write this file',
  },
  'acceptance-lessons.md': {
    owners: ['acceptance-manager'],
  },

  // ── Control-owned files ──
  'orchestration-status.md': {
    owners: ['harness-orchestrator'],
    note: 'plugin writes this; agents read but must not write',
  },
  'working-memory.md': {
    owners: ['harness-orchestrator', 'planning-manager', 'execution-manager'],
    note: 'control owns overall structure',
  },
  'state-index.json': {
    owners: ['harness-orchestrator'],
    note: 'plugin-managed; agents must not write',
  },
  'managed-agent-state-index.json': {
    owners: ['harness-orchestrator'],
    note: 'plugin-managed; agents must not write',
  },
  'harness-plugin-state.json': {
    owners: ['harness-orchestrator'],
    note: 'plugin-managed; agents must not write',
  },
  'route-packet.json': {
    owners: ['harness-orchestrator'],
    note: 'plugin-managed; agents must not write',
  },

  // ── Shared files ──
  'activity.jsonl': {
    owners: ['harness-orchestrator', 'planning-manager', 'execution-manager', 'acceptance-manager',
      'feature-planner', 'capability-planner',
      'code-agent', 'shell-agent', 'browser-agent', 'docs-agent', 'evidence-agent',
      'ui-probe-agent', 'api-probe-agent', 'regression-probe-agent', 'artifact-probe-agent'],
    note: 'append-only shared log',
  },
  'journal.md': {
    owners: ['harness-orchestrator', 'planning-manager', 'execution-manager', 'acceptance-manager',
      'feature-planner', 'capability-planner'],
    note: 'append-only shared journal',
  },
  'handoff.md': {
    owners: ['harness-orchestrator'],
    note: 'generated by control before thread switch',
  },
  'autopilot-status.md': {
    owners: ['harness-orchestrator'],
  },
  'decisions.md': {
    owners: ['harness-orchestrator', 'planning-manager', 'execution-manager', 'acceptance-manager'],
    note: 'append-only decisions log',
  },
};

// ─── Capability and Probe agent lists ───────────────────────────

const CAPABILITY_AGENTS = new Set([
  'browser-agent', 'code-agent', 'shell-agent', 'docs-agent', 'evidence-agent',
]);

const PROBE_AGENTS = new Set([
  'ui-probe-agent', 'api-probe-agent', 'regression-probe-agent', 'artifact-probe-agent',
]);

const MANAGER_AGENTS = new Set([
  'harness-orchestrator', 'feature-planner', 'capability-planner',
  'planning-manager', 'execution-manager', 'acceptance-manager',
]);

// ─── Lookup helpers ─────────────────────────────────────────────

function extractFileName(filePath: string): string | null {
  if (!filePath) return null;
  const parts = filePath.split('/');
  return parts[parts.length - 1] || null;
}

function findRule(fileName: string): FileRule | null {
  return FILE_OWNERSHIP[fileName] || null;
}

/**
 * Check if an actor is allowed to write a file given the current state.
 */
export function canActorWriteFile(
  actor: string,
  filePath: string,
  _state?: GraphStateLike | null,
): { allowed: boolean; reason: string } {
  const fileName = extractFileName(filePath);
  if (!fileName) {
    return { allowed: true, reason: 'no-filename-extracted' };
  }

  // Files outside .agent-memory/ are not governed by this guard
  if (!filePath.includes('.agent-memory') && !filePath.includes('/evidence/')) {
    return { allowed: true, reason: 'outside-agent-memory' };
  }

  const rule = findRule(fileName);
  if (!rule) {
    // Unregistered file — allow but log
    return { allowed: true, reason: 'unregistered-file' };
  }

  // Check direct ownership
  if (rule.owners.includes(actor)) {
    return { allowed: true, reason: 'direct-owner' };
  }

  // Check co-owners
  if (rule.coOwners && rule.coOwners.includes(actor)) {
    return { allowed: true, reason: 'co-owner' };
  }

  return {
    allowed: false,
    reason: `actor "${actor}" is not an owner of "${fileName}" (owners: ${rule.owners.join(', ')})`,
  };
}

/**
 * Return the set of actors allowed to write a file.
 */
export function allowedActorsForFile(filePath: string): string[] {
  const fileName = extractFileName(filePath);
  if (!fileName) return [];
  const rule = findRule(fileName);
  if (!rule) return [];
  return [...rule.owners, ...(rule.coOwners || [])];
}

/**
 * Build a human-readable block message for a denied file write.
 */
export function buildBlockMessage(
  actor: string,
  filePath: string,
  reason: string,
): string {
  const fileName = extractFileName(filePath) || filePath;
  return [
    'Phase-actor authorization blocked this write.',
    `Actor: ${actor}`,
    `File: ${fileName}`,
    `Reason: ${reason}`,
    '',
    'This file is owned by different actor(s) per the harness ownership model.',
    'Recovery:',
    '1. Delegate this write to the correct manager or hand agent.',
    '2. Check .agent-memory/orchestration-status.md for the expected next writer.',
    `3. Allowed writers for ${fileName}: ${allowedActorsForFile(filePath).join(', ') || 'unknown'}`,
    '4. For emergency bypass: add PHASE_GUARD_BYPASS marker to your content.',
  ].join('\n');
}

// ─── Phase legality check for dispatch ──────────────────────────

const PHASE_ACTOR_MAP: Record<string, Set<string>> = {
  'intake': new Set(['harness-orchestrator']),
  'route-selection': new Set(['harness-orchestrator']),
  'planning': new Set(['feature-planner', 'capability-planner', 'planning-manager']),
  'execution': new Set(['execution-manager', 'code-agent', 'shell-agent', 'browser-agent', 'docs-agent', 'evidence-agent']),
  'acceptance': new Set(['acceptance-manager', 'ui-probe-agent', 'api-probe-agent', 'regression-probe-agent', 'artifact-probe-agent']),
  'probe-verification': new Set(['acceptance-manager', 'ui-probe-agent', 'api-probe-agent', 'regression-probe-agent', 'artifact-probe-agent']),
  'complete': new Set([]),  // read-only
  'blocked': new Set(['harness-orchestrator']),
};

/**
 * Check if dispatching (or activating) a given actor is legal in the current phase.
 */
export function isActorLegalForPhase(
  actor: string,
  phase: string,
): { legal: boolean; reason: string } {
  const allowed = PHASE_ACTOR_MAP[phase];
  if (!allowed) {
    return { legal: true, reason: `unknown-phase:${phase}` };
  }

  // Capability hands are always legal in execution phase
  if (phase === 'execution' && CAPABILITY_AGENTS.has(actor)) {
    return { legal: true, reason: 'capability-hand-in-execution' };
  }

  // Probes are always legal in acceptance/probe-verification phases
  if ((phase === 'acceptance' || phase === 'probe-verification') && PROBE_AGENTS.has(actor)) {
    return { legal: true, reason: 'probe-in-acceptance' };
  }

  if (allowed.has(actor)) {
    return { legal: true, reason: 'explicitly-allowed' };
  }

  return {
    legal: false,
    reason: `actor "${actor}" is not allowed in phase "${phase}" (allowed: ${[...allowed].join(', ')})`,
  };
}

/**
 * Primary guard function. Returns a block reason string if the write should be blocked,
 * or null if it should be allowed.
 */
export function guardFileWrite(
  actor: string,
  filePath: string,
  content: string,
  state?: GraphStateLike | null,
): string | null {
  // Bypass marker
  if (content.includes('PHASE_GUARD_BYPASS')) {
    return null;
  }

  const result = canActorWriteFile(actor, filePath, state);
  if (result.allowed) return null;

  return buildBlockMessage(actor, filePath, result.reason);
}
